### ISSUE TITLE
Variants of 'r'

### ISSUE THREAD

**Issue by dharmatech** [naivesound/glitch-orig#2]
It seems that `r` returns a floating point value. It would be nice to also have a random function which returns an integer. So for example: `random_int(4)` would return 0, 1, 2, or 3.

Also, sometimes I'd like to play a random note from a small set. So something like `pick(10, 20, 30)` would return one of those items randomly.

**Comment by zserge** [comment]
Great questions!

Glitch uses floating-point internally for all functions to achieve "smoother" audio output. But every floating point number can be truncated with a bitwise operation. How about `r(100) | 0`? It should return integers from 0 to 100.

Random items from a set can be implemented with `a(index, ...)` function. You may also play with probabilities including the same item multiple times if you want: `a(r(4), 10, 20, 30, 30)`. In this case the result will be 30 in 50% of the cases.

**Comment by dharmatech** [comment]
Both of those work great. Thanks zserge!

**Comment by dharmatech** [comment]
Here's a simple program that (sorta) plays the tones 0 through 7 in sequence. I say "sorta" because if you listen to it, the timing is a bit off when it jumps between the two `seq`s.:

```
sin(
  hz(
    loop(30,
      seq(100, 0, 1, 2, 3),
      seq(100, 4, 5, 6, 7))))
```

Is there a way to select one or the other `seq`s randomly each time through? I.e. something like this:

```
sin(
  hz(
    loop(30,
      a(r(2),  
        seq(100, 0, 1, 2, 3),
        seq(100, 4, 5, 6, 7)))))
```

But of course, that doesn't quite sound like what I'm going for. :-)

**Comment by zserge** [comment]
@dharmatech It is likely to make your expression bigger, but I would rewrite it in different order:

`i=r(2),sin(hz(loop(30, seq(100, a(i,0,4), a(i,1,5), a(i,2,6), a(i,3,7)))))`
